# Generated by Django 2.2.9 on 2020-02-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Tittel'),
        ),
    ]
