# Generated by Django 4.0 on 2021-12-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['creator', 'name'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temaer'},
        ),
    ]
